/*Imagine you are working on the development of a solar power calculator. The calculator needs to estimate how much solar energy can be generated over a certain period, assuming that the solar panels produce a specific amount of energy every day.

You have the following parameters:

x: The amount of energy (in kilowatt-hours) generated by the solar panels in one day.
n: The number of days the solar panels will operate.
Your task is to implement a function that calculates the total energy generated over n days. The formula to calculate the energy over multiple days is the power of x raised to n, i.e., x^n, where x is the daily energy production, and n is the number of days.

Implement a function pow(x, n) that calculates x raised to the power of n (i.e., x^n).*/
#include <iostream>
using namespace std;

double pow(double x,int n){
    if (n == 0)
        return 1;
    return pow(x, n - 1) * x;
}

int main(){
    double x;
    int n;
    cin >> x >> n;
    cout << pow(x, n) << " kWh";
    return 0;
}